apiVersion: batch/v1
kind: Job
metadata:
  name: pg-backup-job
spec:
  template:
    spec:
      containers:
      - name: pg-backup
        image: sbernardellodxc/pg-backup:latest
        envFrom:
        - secretRef:
            name: pg-backup-secrets
      restartPolicy: Never
  backoffLimit: 4